/**
 * inspectLayerStructure.js
 *
 * Phase 0 — Full shape inventory with all properties needed for semantic inference.
 * Read-only. No mutations.
 *
 * Returns a structured layer tree with position, size, type, text properties,
 * fill/stroke info, and parent-child relationships.
 *
 * Usage: paste into execute_code. Pass the result to inferSemanticNames.js (local analysis).
 */

const page = penpot.currentPage;
const allShapes = page.findShapes();

// Find page width from top-level frames
const topLevel = allShapes.filter(s => !s.parentId);
const estimatedPageWidth = Math.max(100, ...topLevel.map(s => s.width || 0));
const estimatedPageHeight = Math.max(100, ...topLevel.map(s => (s.y || 0) + (s.height || 0)));

function isAutoGenerated(name) {
  return /^(Frame|Rectangle|Group|Ellipse|Text|Path|Bool|Image|Component|Vector)\s*\d*$/i.test(name || '');
}

function isAlreadySemantic(name) {
  return /^(header|footer|nav|main|section|article|aside|form|button|input|select|label|h[1-6]|p[-_]|ul|ol|li[-_]|img|svg|dialog|figure|figcaption|a[-_]|span[-_]|small|caption|icon[-_]|div[-_])/i.test(name || '');
}

const layers = allShapes.map(shape => {
  const name = shape.name || '';
  return {
    id: shape.id,
    name,
    type: shape.type,
    nameStatus: isAlreadySemantic(name) ? 'semantic' : isAutoGenerated(name) ? 'auto-generated' : 'custom',
    // Position and size
    x: Math.round(shape.x || 0),
    y: Math.round(shape.y || 0),
    width: Math.round(shape.width || 0),
    height: Math.round(shape.height || 0),
    // Relative position hints
    isFullWidth: (shape.width || 0) >= estimatedPageWidth * 0.8,
    isAtTop: (shape.y || 0) < 120,
    isAtBottom: (shape.y || 0) > estimatedPageHeight * 0.8,
    // Hierarchy
    parentId: shape.parentId || null,
    childCount: shape.children ? shape.children.length : 0,
    childTypes: shape.children
      ? [...new Set(shape.children.map(c => c.type))].join(',')
      : '',
    // Fills & strokes
    hasSolidFill: !!(shape.fills && shape.fills.some(f => f.fillType === 'solid')),
    hasImageFill: !!(shape.fills && shape.fills.some(f => f.fillType === 'image')),
    fillColor: shape.fills && shape.fills[0]?.fillType === 'solid'
      ? shape.fills[0].fillColor
      : null,
    hasStrokeOnly: !!(
      shape.strokes && shape.strokes.length > 0 &&
      (!shape.fills || shape.fills.length === 0 || shape.fills.every(f => f.fillOpacity === 0))
    ),
    borderRadius: shape.borderRadius || 0,
    // Typography
    isText: shape.type === 'text',
    fontSize: shape.fontSize || null,
    fontWeight: shape.fontWeight || null,
    fontFamily: shape.fontFamily || null,
    characters: shape.characters ? shape.characters.substring(0, 60) : null,
    // Component
    isComponentInstance: !!shape.componentId && !shape.isMainComponent,
    isMainComponent: !!shape.isMainComponent,
    // Layout
    hasFlexLayout: !!shape.layout,
    layoutDir: shape.layout?.dir || null,
  };
});

return {
  pageId: page.id,
  pageName: page.name,
  totalShapes: allShapes.length,
  estimatedPageWidth,
  estimatedPageHeight,
  layers,
  stats: {
    autoGenerated: layers.filter(l => l.nameStatus === 'auto-generated').length,
    alreadySemantic: layers.filter(l => l.nameStatus === 'semantic').length,
    custom: layers.filter(l => l.nameStatus === 'custom').length,
    componentInstances: layers.filter(l => l.isComponentInstance).length,
    textNodes: layers.filter(l => l.isText).length,
  },
};
